config/routes.rb
Rails.application.routes.draw do

  #Index page is sites#index
  root 'sites#index'

  #Routes for devise
  devise_for :users
  resources :users, only: [:show, :edit]

  #Routes for friendships
  resources :friendships, only: [:index, :create, :destroy, :show]

  #Route for the ajax get request to the other editor's document
  get '/documents', to: 'documents#index'
  #Route for the ajax put request to update the current_user's editor's document's text
  put '/documents', to: 'documents#update'
  #Route for running the code
  post '/documents', to: 'documents#run'

  #Route for the ajax get request to the other editor's document
  get '/documents', to: 'documents#index'
  #Route for the ajax put request to update the current_user's editor's document's text
  put '/documents', to: 'documents#update'

  #Route for the about us page 
  get '/about', to: 'sites#about'
  #Route for the contact us page
  get '/contact', to: 'sites#contact'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user #User who initiated the relationship
  belongs_to :friend, :class_name => 'User' #User who has been friended

  validates :user, presence: true
  validates :friend, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  validates :full_name, presence: true, length: { minimum: 2 }
  validates :profile_name, presence: true, uniqueness: true, length: { minimum: 3 }

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :documents

  #For CarrierWave Image Upload
  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Call the configure_permitted_parameters method if we're in a devise controller
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  #Workaround so that we can use other attributes in our user model, which was generated by devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:full_name, :profile_name, :email, :password, :level, :avatar)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:profile_name, :email, :password, :password_confirmation, :level, :avatar, :current_password)}
  end
end

app/controllers/documents_controller.rb
# Timeout in for help in sandboxing the code evaluation
require 'timeout'

class DocumentsController < ApplicationController

  def index
    @document = Document.where(friendship_id: params["document"]["friendship_id"], user_id: params["document"]["user_id"])[0]
    respond_to do |format|
      format.json { render json: @document, status: :ok}
    end
  end

  def update
    @document = Document.where(friendship_id: params["document"]["friendship_id"], user_id: current_user.id)[0]
    updated_attributes = params.require(:document).permit(:text, :friendship_id, :user_id)
    @document.update_attributes(updated_attributes)
    respond_to do |format|
      format.json { render json: @document, status: :ok }
    end
  end

  def run
    @code_sample = params[:text]
    std_output = StringIO.new
    std_error = StringIO.new

    # If the interpreter takes longer than 20 seconds, assume we are in an
    # infinite loop and terminate.
    Timeout.timeout(20) do
      begin
        $stdout = std_output
        $stderr = std_error
        # Safely evaluate the code within a sandbox at level 3 safety
        @code_result = safe(:level => 3) { eval @code_sample }
      rescue SyntaxError => se
        @syntax_error = se
      rescue NameError => ne
        @syntax_error = ne
      rescue TypeError => te
        @syntax_error = te
      rescue ArgumentError => ae
        @syntax_error = ae
      ensure
        $stdout = STDOUT
        $stderr = STDERR
      end
    end

    @std_error = std_error.string
    @std_output = std_output.string

    @code_result = {"code" => @code_result}
    @syntax_error = {"code" => @syntax_error.to_s}
    @std_output = {"code" => @std_output}
   
    if @std_output["code"] != ""
      respond_to do |format|
        format.json { render json: @std_output, status: :ok }
      end
    else
      if @syntax_error["code"] == ""
        respond_to do |format|
          format.json { render json: @code_result, status: :ok }
        end
      else
        respond_to do |format|
          format.json { render json: @syntax_error, status: :ok }
        end
      end
    end
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
  include FriendshipsHelper

  before_action :authenticate_user!
  before_action :check_friendship_owner, only: [:show]
  
  def index
    @users = User.all
    @friendships = Friendship.all
  end

  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      # At creation, the owner is whoever the current user is, which means the user who initiated the add
      @document1 = current_user.documents.build(text: "", friendship_id: @friendship.id)
      @document1.save
      # At creation, the owner is the user who was friended, i.e. the one with friend_id
      friend = User.find(params[:friend_id])
      @document2 = friend.documents.build(text: "", friendship_id: @friendship.id)
      @document2.save
      flash[:notice] = "Added friend."
      redirect_to friendships_path
    else
      flash[:notice] = "Unable to add friend."
    end
  end

  def destroy
    @friendship = current_user.friendships.where(id: params[:id])
    if @friendship.empty?
      @friendship = current_user.inverse_friendships.find(params[:id])
      @friendship.destroy
      @document = Document.find_by_friendship_id(@friendship.id)
      @document.destroy
      flash[:notice] = "Removed friendship."
      redirect_to friendships_path
    else
      @friendship = current_user.friendships.find(params[:id])
      @friendship.destroy
      @document = Document.find_by_friendship_id(@friendship.id)
      @document.destroy
      flash[:notice] = "Removed friendship."
      redirect_to friendships_path
    end
  end

  def show
    #Editing session
    @documents = Document.where(friendship_id: params[:id])
    @documents.each do |document|
      if document.user_id == current_user.id
        #document1 is the current_user's document
        @document1 = document
        @current_user_id = current_user.id
        @current_user = current_user
      else
        #document2 is the friend's document
        @document2 = document
        @friend_id = @document2.user_id
        @friend = User.find(@friend_id)
      end
    end
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    #for signed-in users, skip landing page and redirect to friends page
    if user_signed_in?
      redirect_to friendships_path
    else
      render 'index'
    end
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :authenticate_user!
  before_action :check_user_page_owner, only: [:show]

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def check_friendship_owner
    friendship = current_user.friendships.where(:id => params[:id])
    if friendship.nil?
      redirect_to friendships_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_user_page_owner
    user = User.find(params[:id])
    if user.id != current_user.id
      redirect_to friendships_path
    end
  end
end

app/views/friendships/index.html.erb
<div class="row">
  <div class="friends">
    <div class="col-md-6">
      <h2>Add Friends</h2>
      <% current_user_friends = [] %>
      <% current_user.friends.each do |friend| %>
        <% current_user_friends.push friend %>
      <% end %>
      <% current_user.inverse_friends.each do |inverse_friend| %>
        <% current_user_friends.push inverse_friend %>
      <% end %>
      <% @users.each do |user| %>
        <p>
          <% unless current_user_friends.include? user %>
            <% unless user == current_user %>
              <div class='friendships-img'><%= image_tag user.avatar %></div>
              <%= user.profile_name %><br/>
              Level: <%= user.level %><br/>
              <%= link_to "Add Friend", friendships_path(friend_id: user), method: :post %>
            <% end %>
          <% end %>
        </p>
      <% end %>
   </div>

    <div class="col-md-6">
      <h2>Your Friends</h2>
      <% current_user.inverse_friendships.each do |friendship| %>
      <p>
        <div class='friendships-img'><%= image_tag friendship.user.avatar %></div>
        <%= friendship.user.profile_name %><br/>
        Level: <%= friendship.user.level %><br/>
        <%= link_to "Code with me", friendship_path(friendship) %><br/>
        <%= link_to "Remove Friend", friendship, data: { confirm: "Are you sure?" }, method: :delete %>
      </p>
      <% end %>
      <% current_user.friendships.each do |friendship| %>
      <p>
        <div class='friendships-img'><%= image_tag friendship.friend.avatar %></div>
        <%= friendship.friend.profile_name  %><br/>
        Level: <%= friendship.friend.level %><br/>
        <%= link_to "Code with me", friendship_path(friendship) %><br/>
        <%= link_to "Remove Friend", friendship, data: { confirm: "Are you sure?" }, method: :delete %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/friendships/show.html.erb
<div class="row" id="editors">
  <div class="col-md-6">
   <h3><%=@current_user.profile_name%>'s code</h3>
    <textarea class="e1" id="<%=@current_user_id%>" rows="18"><%= @document1.text %></textarea>
    <textarea readonly class="i1" rows="4"></textarea>
    <center><button class="btn btn-default" id="run1">Run</button></center>
  </div>
  <div class="col-md-6">
    <h3><%=@friend.profile_name%>'s code</h3>
    <textarea class="e2" id="<%=@friend_id%>" rows="18"><%= @document2.text %></textarea>
    <textarea readonly class="i2" rows="4"></textarea>
    <center><button class="btn btn-default" id="run2">Run</button></center>
  </div>    
</div>
<script>
  $('.e1').ace({ theme: 'twilight', lang: 'ruby' })
  $('.e2').ace({ theme: 'chrome', lang: 'ruby' })
</script>

app/views/layouts/_footer.html.erb
<!-- footer -->
  <div class="navbar navbar-custom footer">
    <div class="container footer_links">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Contact', '/contact' %></li>
          <li><%= link_to 'About Us', '/about' %></li>
        </ul>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<!-- top navbar -->
<nav class="navbar navbar-custom" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PairED</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Friends', friendships_path %></li>
          <li><%= link_to 'My Profile',user_path(current_user) %></li>
          <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'About Us', '/about' %></li>
          <li><%= link_to 'Contact', '/contact' %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %> 
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairED</title>
  <!-- 
       Did you have an issue with fonts in production?  I don't think this
       will work on heroku.  What should work is:
       href='//fonts.googleapis.com/css?family=Arvo'
  -->
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<!-- Good job here.  Well designed layout -->
<%= render "layouts/navbar" %>

<div class="container body">
<%= yield %>
</div>
  
<%= render "layouts/footer" %>

</body>
</html>

app/views/sites/about.html.erb
<!-- Info about the app and the team -->
<div class="row">

  <h1>About us!</h1>
  <!-- Comma after PairEd -->
  <article>We are PairEd a group of Web development students passionate <br />
  about teaching others about learning how to code 
  and about social collaboration.</article>
  <br />
  <h2>Team Members</h2>

    <li>Blair Cuny - Design, Styling and User Experience</li>
    <li>Steven Miller - Javacsript, Ajax and Backend Development</li>
    <li>Warsama Gabriel - Controller, Request and Model Testing</li>

</div>

app/views/sites/contact.html.erb
<!-- A way to contact us -->

<div class="row">

  <h1>Contact Us</h1>

  <p>Please Visit us on Github</p>

  <a href="https://github.com/PairedCodingApp/PairedCodingApp">PairEd on Github</a>

</div>

app/views/sites/index.html.erb
<!-- Landing page, app name unknown -->
<div class="row">
  <div class="landing">
    <h3>Learning to code in Ruby?</h3>
    <h2>Pair Program anytime, anywhere.</h2>
    <h1> PairED </h1>
    <img src='http://i.imgur.com/aXgeqVy.png'><br/><br/><br/>
    <% unless user_signed_in? %>
      <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile">

  <h1>My Profile</h1><br/>
    <div class='profile-img'><%= image_tag @user.avatar_url.to_s %></div><br/>
    <p>
      Username:<br/><strong><%= @user.profile_name.capitalize %></strong><br/><br/>
      Email:<br/><strong><%= @user.email %></strong><br/><br/>
      Ruby Level:<br/><strong><%= @user.level %></strong><br/><br/>
    </p>
    <%= link_to 'Edit Account', edit_user_registration_path, class: 'btn btn-primary' %>
</div>